### ISSUE TITLE
MISC_DecodeSpcharNumberTestが死ぬ

### ISSUE THREAD

**Issue by mtasaka** [JDimproved/JDim#1078]
cd1861a27ac3ca3c08abc4d5fdecff1377bd4532 で `MISC_DecodeSpcharNumberTest` が死にます

```
[tasaka1@localhost test]$  ./gtest_jdim --gtest_filter=MISC_DecodeSpcharNumberTest.result_ok
Running main() from /builddir/build/BUILD/googletest-release-1.12.1/googletest/src/gtest_main.cc
Note: Google Test filter = MISC_DecodeSpcharNumberTest.result_ok
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from MISC_DecodeSpcharNumberTest
[ RUN      ] MISC_DecodeSpcharNumberTest.result_ok
=================================================================
==1790352==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000002353c03 at pc 0x000001c393a4 bp 0x7fffdc321d70 sp 0x7fffdc321d68
READ of size 4 at 0x000002353c03 thread T0
    #0 0x1c393a3 in memcpy /usr/include/bits/string_fortified.h:29
    #1 0x1c393a3 in MISC::decode_spchar_number(char const*, int, int) ../src/jdlib/miscutil.cpp:1608
    #2 0xd20a99 in TestBody ../test/gtest_jdlib_miscutil.cpp:2003
    #3 0x7faca19bc9eb in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [clone .constprop.0] (/lib64/libgtest.so.1.12.1+0x4e9eb)
    #4 0x7faca19a97e5 in testing::Test::Run() (/lib64/libgtest.so.1.12.1+0x3b7e5)
    #5 0x7faca19a99ec in testing::TestInfo::Run() (/lib64/libgtest.so.1.12.1+0x3b9ec)
    #6 0x7faca19a9b36 in testing::TestSuite::Run() (/lib64/libgtest.so.1.12.1+0x3bb36)
    #7 0x7faca19b5c34 in testing::internal::UnitTestImpl::RunAllTests() (/lib64/libgtest.so.1.12.1+0x47c34)
    #8 0x7faca19b491f in testing::UnitTest::Run() (/lib64/libgtest.so.1.12.1+0x4691f)
    #9 0x7faca19dd153 in main (/lib64/libgtest_main.so.1.12.1+0x1153)
    #10 0x7fac9ec4a50f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #11 0x7fac9ec4a5c8 in __libc_start_main_impl ../csu/libc-start.c:381
    #12 0x6017c4 in _start (/home/tasaka1/rpmbuild/fedora-specific/jd/rawhide/jd-0.8.0/JDim/redhat-linux-build/test/gtest_jdim+0x6017c4)

0x000002353c03 is located 61 bytes to the left of global variable '*.LC35' defined in '/tmp/cc0p2TOw.ltrans27.o' (0x2353c40) of size 44
  '*.LC35' is ascii string 'MISC::decode_spchar_number( "&#xC;", 3, 4 )'
0x000002353c06 is located 0 bytes to the right of global variable '*.LC34' defined in '/tmp/cc0p2TOw.ltrans27.o' (0x2353c00) of size 6
  '*.LC34' is ascii string '&#xC;'
SUMMARY: AddressSanitizer: global-buffer-overflow /usr/include/bits/string_fortified.h:29 in memcpy
Shadow bytes around the buggy address:
  0x000080462730: 00 00 00 f9 f9 f9 f9 f9 00 00 00 00 03 f9 f9 f9
  0x000080462740: f9 f9 f9 f9 00 00 00 00 01 f9 f9 f9 f9 f9 f9 f9
  0x000080462750: 00 00 00 00 01 f9 f9 f9 f9 f9 f9 f9 00 00 00 00
  0x000080462760: 03 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 f9 f9 f9 f9
  0x000080462770: 00 00 00 04 f9 f9 f9 f9 00 00 00 06 f9 f9 f9 f9
=>0x000080462780:[06]f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 04 f9 f9
  0x000080462790: f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9 06 f9 f9 f9
  0x0000804627a0: f9 f9 f9 f9 00 00 00 00 00 04 f9 f9 f9 f9 f9 f9
  0x0000804627b0: 03 f9 f9 f9 f9 f9 f9 f9 07 f9 f9 f9 f9 f9 f9 f9
  0x0000804627c0: 00 00 00 00 00 05 f9 f9 f9 f9 f9 f9 05 f9 f9 f9
  0x0000804627d0: f9 f9 f9 f9 07 f9 f9 f9 f9 f9 f9 f9 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1790352==ABORTING
```
`decode_spchar_number` の `decode_spchar_number_raw` の呼び方を見ると、 `decode_spchar_number` の第3引数の`const int lng`は第1引数の文字列の `"&#"` または  `"&#x"` の部分を引いた長さを与えるべきのように見えます。

例えば、`EXPECT_EQ( 0xC, MISC::decode_spchar_number( "&#xC;", 3, 4 ) );` は  `EXPECT_EQ( 0xC, MISC::decode_spchar_number( "&#xC;", 3, 1) );`ではありませんか？

**Comment by ma8ma** [comment]
@mtasaka 
ご指摘のとおりです。テストケースの引数を正しい値に直して修正いたします。

**Comment by ma8ma** [comment]
報告ありがとうございました。:+1:
このようなミスを減らすためにGitHubのCIでAddressSanitizerを試してみたいと思います。

**Comment by ma8ma** [comment]
ASanを試してみました。 https://github.com/ma8ma/JDim/pull/70
期待通り動いたのでCIのjobを調整・入れ替えるなどして導入したいと思います。
