### ISSUE TITLE
スレビューでスレを表示したときに異常終了することがある

### ISSUE THREAD

**Issue by ma8ma** [JDimproved/JDim#1392]
スレビューでスレを表示したときに異常終了することがある

**バグの説明**

#1390 の修正(#1391) した後も同じエラーチェックが出て落ちると報告がスレにありました。

<https://next2ch.net/test/read.cgi/linux/1654053581/197-198n>

こちらで確認を行ったところスレビューでスレを表示したときレスが少なくスクロールしない、
つまりスクロールバーのノブがバーの全体に広がっているときに異常終了することがあったので報告します。

**再現の方法**

1. gccにある追加のエラーチェックを有効にしてjdimをビルドします。
   ```sh
   $ meson setup debug -Doptimization=g -Dcpp_args="-Wp,-D_GLIBCXX_ASSERTIONS"
   ```
2. テスト用のキャッシュでjdimを起動します。
   ```sh
   $ JDIM_CACHE=$(pwd)/Test_new ./debug/src/jdim
   ```
3. メインウインドウのサイズを小さく変更します。
4. レス数が少ないスレを開きます。
5. メインウインドウのサイズを最大化してスクロールバーのノブをバー全体に伸ばします。
6. スレのスクロール操作を行います。
5. JDimが異常終了してコンソールにエラーメッセージが表示されます。
   ```sh
   /usr/include/c++/13/bits/stl_algo.h:3669: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = double]: Assertion '!(__hi < __lo)' failed.
   中止 (コアダンプ)
   ```

snapのedgeチャンネルでも発生しました。

**やりたかったこと・期待する結果**

メインウインドウを最大化しても異常終了しない。

**スクリーンショット**

なし

**動作環境**

masterブランチからビルド
```
[バージョン] JDim 0.11.0-20240505(git:60a7dad0d2)
[ディストリ ] Ubuntu 23.10 (x86_64)
[パッケージ] バイナリ/ソース( <配布元> )
[ DE／WM ] KDE
[　gtkmm 　] 3.24.8
[　glibmm 　] 2.66.6
[　TLS lib　] GnuTLS 3.8.1
[ そ の 他 ] 
```

snap edgeチャンネル
```
[バージョン] JDim 0.11.0-20240505(git:60a7dad0d2)
[ディストリ ] Ubuntu Core 20 (x86_64)
[パッケージ] Snap (JDimproved project)
[ DE／WM ] KDE
[　gtkmm 　] 3.24.3
[　glibmm 　] 2.64.4
[　TLS lib　] GnuTLS 3.6.13
[オプション ] '--with-pangolayout''--disable-compat-cache-dir'
[ そ の 他 ] 
```

**追加の情報**

gdbのバックトレース
```cpp
/usr/include/c++/13/bits/stl_algo.h:3669: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = double]: Assertion '!(__hi < __lo)' failed.

Thread 1 "jdim" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: そのようなファイルやディレクトリはありません.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff60428e6 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff60268b7 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff64e219f in std::__glibcxx_assert_fail(char const*, int, char const*, char const*) () at /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x000055555594a36d in std::clamp<double> (__val=@0x7fffffff9d28: 450, __lo=@0x7fffffff9d50: 0, __hi=@0x7fffffff9d70: -249)
    at /usr/include/c++/13/bits/stl_algo.h:3669
#7  0x000055555593f9a2 in ARTICLE::DrawAreaBase::exec_scroll (this=this@entry=0x5555574ba4c0) at ../src/article/drawareabase.cpp:3286
(snip)
(gdb) frame 6
#6  0x000055555594a36d in std::clamp<double> (__val=@0x7fffffff9d28: 450, __lo=@0x7fffffff9d50: 0, __hi=@0x7fffffff9d70: -249)
    at /usr/include/c++/13/bits/stl_algo.h:3669
3669          __glibcxx_assert(!(__hi < __lo));
(gdb) p __hi
$1 = (const double &) @0x7fffffff9d70: -249
(gdb) p __lo
$2 = (const double &) @0x7fffffff9d50: 0
#7  0x000055555593f9a2 in ARTICLE::DrawAreaBase::exec_scroll (this=this@entry=0x5555574ba4c0) at ../src/article/drawareabase.cpp:3286
3286        const int y_new = static_cast<int>(std::clamp<double>( y, 0, adjust->get_upper() - adjust->get_page_size() ));
```

**Comment by ma8ma** [comment]
git bisectで調べた結果です。
```cpp
2a3cad6e5b08ee8a7b970865eb1245db73ef0643 is the first bad commit
commit 2a3cad6e5b08ee8a7b970865eb1245db73ef0643
Author: (snip)
Date:   Sat May 4 23:02:19 2024 +0900

    Fix compiler warning for -Wold-style-cast part10

    C言語スタイルのキャストを使用しているとclangに指摘されたため
    C++スタイルのキャスト`static_cast<...>(value)`に変更して
    コンパイラー警告を修正します。

    また、関数形式マクロの`MIN()`と`MAX()`を組み合わせて値を範囲内に
    収める処理を`std::clamp()`に置き換えます。

    clang-17のレポート (file pathを一部省略)
    ```
    src/article/drawareabase.cpp:3290:23: warning: use of old-style cast [-Wold-style-cast]
     3290 |     const int y_new = (int)MAX( 0, MIN( adjust->get_upper() - adjust->get_page_size() , y ) );
          |                       ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/article/preference.cpp:319:62: warning: use of old-style cast [-Wold-style-cast]
      319 |             if( pos != std::string::npos ) number_end = MIN( (int)vec_abone_res.size(), MAX( number, atoi( num_str.substr( pos + 1 ).c_str() ) ) );
          |                                                              ^    ~~~~~~~~~~~~~~~~~~~~
    src/article/preference.cpp:319:62: warning: use of old-style cast [-Wold-style-cast]
      319 |             if( pos != std::string::npos ) number_end = MIN( (int)vec_abone_res.size(), MAX( number, atoi( num_str.substr( pos + 1 ).c_str() ) ) );
          |                                                              ^    ~~~~~~~~~~~~~~~~~~~~
    ```

 src/article/drawareabase.cpp | 2 +-
 src/article/preference.cpp   | 7 ++++++-
 2 files changed, 7 insertions(+), 2 deletions(-)

```
